### ISSUE TITLE
Feature request: Support for formatting the python code in jupyter notebooks

### ISSUE THREAD

**Issue by MrinalJain17** [ambv/black#298]
*Jupyter notebooks* are quite popular and are used a lot (especially in tasks related to data analysis, visualization etc.).
These notebooks are also used as presentations and tutorials. 
It would be great if `black` could format the code within the cells of the notebooks.

**Comment by jgirardet** [comment]
https://github.com/csurfer/blackcellmagic

**Comment by MrinalJain17** [comment]
This is great.. Thanks!

**Comment by srstevenson** [comment]
@cdeil and others interested in being able to format notebooks from the command line: [mcflugen/nbblack](https://github.com/mcflugen/nbblack) is a fairly new project that looks to offer that.

**Comment by MarvinT** [comment]
It's pretty easy to configure the code-prettify Nbextension to use Black. Heres the configuration I use and some install instructions.

https://gist.github.com/MarvinT/a072aa992e977496974aaf492287b08c
and 
https://marvint.github.io/Black-Jupyter/

**Comment by MarcoGorelli** [comment]
> Is there something like
> 
> ```
> $ black-notebook analysis.ipynb
> ```
> 
> that runs black on all code cells in the notebook(s) from the command line and saves them back in-place?
> 
> I guess it's just ~ 10 lines using the Jupyter API, but I'd still prefer using it over writing it if someone has written that already.

@cdeil you can do this with nbQA https://github.com/nbQA-dev/nbQA

e.g.

```bash
nbqa black notebook.ipynb --nbqa-mutate
```

It'll also work as a pre-commit hook, e.g. you could have this in `.pre-commit-config.yaml`:

```yaml
repos:
- repo: 'https://github.com/nbQA-dev/nbQA'
    rev: 0.3.0
    hooks:
    - id: nbqa
        args:
        - black
        name: nbqa-black
        alias: nbqa-black
        additional_dependencies:
        - black
```

and this in `pyproject.toml`:

```toml
[tool.nbqa.config]
black = "pyproject.toml"

[tool.nbqa.mutate]
black = 1

[tool.nbqa.ignore_cells]
black = "%%cython"
```
