### ISSUE TITLE
[Feature Request] Github pull request check

### ISSUE THREAD

**Issue by MarvinT** [ambv/black#609]
I think it would be very useful to implement a github check that checked adherence to Black style. I'm thinking of something that could be run via something like travis-ci.

It's nice that I install black on my machines and adhere to it, but I would like to make sure others adhere to it when submitting a PR to a repo without having for me to go and install it on their machine.

**Comment by JelleZijlstra** [comment]
You can use `black --check` for this in a CI hook. See Black's own Travis configuration for an example: https://github.com/ambv/black/blob/master/.travis.yml#L11.

**Comment by MarvinT** [comment]
Is there a clean way to do this in a package that builds using python versions <3.6?

Ideally, I'd want something like:
```
jobs:
  include:
    - name: 'black'
      python: 3.6
      install: pip install black
      script: black --check --verbose .
```
but this doesn't seem to be allowed by travis. I guess I could put a pip install and then black --check in a script file and call the script... Any recommendations?
